#include "RenderAPID3D11.h"
namespace Joestar {
	DXGI_FORMAT ImageFormatMapping[]{
		DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
		DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
		DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
		DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
		DXGI_FORMAT_R11G11B10_FLOAT,
		DXGI_FORMAT_D24_UNORM_S8_UINT,
		DXGI_FORMAT_D32_FLOAT_S8X24_UINT
	};
	DXGI_FORMAT GetImageFormatVK(ImageFormat fmt)
	{
		return ImageFormatMapping[(U32)fmt];
	}

	const D3D_SRV_DIMENSION ViewDimensionMapping[]{
		D3D11_SRV_DIMENSION_TEXTURE1D,
		D3D11_SRV_DIMENSION_TEXTURE2D,
		D3D11_SRV_DIMENSION_TEXTURE3D,
		D3D11_SRV_DIMENSION_TEXTURECUBE,
		D3D11_SRV_DIMENSION_TEXTURE1DARRAY,
		D3D11_SRV_DIMENSION_TEXTURE2DARRAY,
		D3D11_SRV_DIMENSION_TEXTURECUBEARRAY
	};
	D3D_SRV_DIMENSION GetViewDimensionD3D(ImageViewType type)
	{
		return ViewDimensionMapping[(U32)type];
	}


	const D3D11_RTV_DIMENSION RTVDimensionMapping[]{
		D3D11_RTV_DIMENSION_TEXTURE1D,
		D3D11_RTV_DIMENSION_TEXTURE2D,
		D3D11_RTV_DIMENSION_TEXTURE3D,
		D3D11_RTV_DIMENSION_TEXTURE2D,
		D3D11_RTV_DIMENSION_TEXTURE1DARRAY,
		D3D11_RTV_DIMENSION_TEXTURE2DARRAY,
		D3D11_RTV_DIMENSION_TEXTURE2DARRAY
	};
	D3D11_RTV_DIMENSION GetRTVDimensionD3D(ImageViewType type)
	{
		return RTVDimensionMapping[(U32)type];
	}


	const D3D11_DSV_DIMENSION DSVDimensionMapping[]{
		D3D11_DSV_DIMENSION_TEXTURE1D,
		D3D11_DSV_DIMENSION_TEXTURE2D,
		D3D11_DSV_DIMENSION_TEXTURE2D,
		D3D11_DSV_DIMENSION_TEXTURE2D,
		D3D11_DSV_DIMENSION_TEXTURE1DARRAY,
		D3D11_DSV_DIMENSION_TEXTURE2DARRAY,
		D3D11_DSV_DIMENSION_TEXTURE2DARRAY
	};
	D3D11_DSV_DIMENSION GetDSVDimensionD3D(ImageViewType type)
	{
		return DSVDimensionMapping[(U32)type];
	}
}