#pragma once
#ifndef _JOESTAR_GRAPHICS_DEF_H_
#define _JOESTAR_GRAPHICS_DEF_H_
enum GFX_API {
	GFX_API_OPENGL = 0,
	GFX_API_VULKAN,
	GFX_API_D3D11,
	GFX_API_D3D12,
	GFX_API_INVALID
};

enum VERTEX_ATTRIBUTE {
	VERTEX_POS = 0,
	VERTEX_NORMAL,
	VERTEX_COLOR,
	VERTEX_TEXCOORD,
	VERTEX_ATTRIB_COUNT
};

enum BUILTIN_MATRIX {
	BUILTIN_MATRIX_MODEL = 0,
	BUILTIN_MATRIX_VIEW,
	BUILTIN_MATRIX_PROJECTION
};

struct BuiltinMatrixCmdData {
	BUILTIN_MATRIX matrixType;
	void* data;
};

const int VERTEX_ATTRIBUTE_SIZE[] = { 3, 3, 3, 2 };
#endif